# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
source "https://gitlab.ozon.ru/ios_common/cocoa-pods-specs"

inhibit_all_warnings!

target 'Strings' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "SwiftGen"
  pod 'R.swift'

  

end
