//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func validate() throws {

  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 2 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var infoPlist: infoPlist { .init(source: .init(bundle: bundle, tableName: "InfoPlist", preferredLanguages: preferredLanguages, locale: locale)) }
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    func infoPlist(preferredLanguages: [String]) -> infoPlist {
      .init(source: .init(bundle: bundle, tableName: "InfoPlist", preferredLanguages: preferredLanguages, locale: locale))
    }
    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.infoPlist` struct is generated, and contains static references to 2 localization keys.
    struct infoPlist {
      let source: RswiftResources.StringResource.Source

      /// en translation: Strings
      ///
      /// Key: CFBundleDisplayName
      ///
      /// Locales: en, ru
      var cfBundleDisplayName: RswiftResources.StringResource { .init(key: "CFBundleDisplayName", tableName: "InfoPlist", source: source, developmentValue: "Strings", comment: nil) }

      /// en translation: This app needs the camera to scan barcodes
      ///
      /// Key: NSCameraUsageDescription
      ///
      /// Locales: en, ru
      var nsCameraUsageDescription: RswiftResources.StringResource { .init(key: "NSCameraUsageDescription", tableName: "InfoPlist", source: source, developmentValue: "This app needs the camera to scan barcodes", comment: nil) }
    }

    /// This `_R.string.localizable` struct is generated, and contains static references to 3 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// en translation: Hello, world!
      ///
      /// Key: Hello.world
      ///
      /// Locales: en, ru
      var helloWorld: RswiftResources.StringResource { .init(key: "Hello.world", tableName: "Localizable", source: source, developmentValue: "Hello, world!", comment: nil) }

      /// en translation: %#@items@
      ///
      /// Key: Hello.worlds
      ///
      /// Locales: en, ru
      var helloWorlds: RswiftResources.StringResource1<Int> { .init(key: "Hello.worlds", tableName: "Localizable", source: source, developmentValue: "%#@items@", comment: nil) }

      /// en translation: Help me
      ///
      /// Key: Help.me
      ///
      /// Locales: en, ru
      var helpMe: RswiftResources.StringResource { .init(key: "Help.me", tableName: "Localizable", source: source, developmentValue: "Help me", comment: nil) }


      /// en translation: %#@items@
      ///
      /// Key: Hello.worlds
      ///
      /// Locales: en, ru
      func helloWorlds(items value1: Int) -> String {
        String(format: helloWorlds, value1)
      }

      /// en translation: %#@items@
      ///
      /// Key: Hello.worlds
      ///
      /// Locales: en, ru
      @available(*, deprecated, message: "Use R.string(preferredLanguages:).*.* instead")
      func helloWorlds(items value1: Int, preferredLanguages: [String]) -> String {
        String(format: helloWorlds, preferredLanguages: preferredLanguages, value1)
      }
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }
  }
}